import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ReactNode} from "react";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

const pretendard = localFont({
    src: "./fonts/PretendardVariable.woff2",
    display: 'swap',
    weight: '45 920',
    variable: '--font-pretendard',
});

export const metadata: Metadata = {
    title: "Sunrin SSF24",
    description: "Generated by create next app",
};


export default function RootLayout({children,}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="ko">
        <body className={`${pretendard.variable} ${pretendard.className}`}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
